[tool.poetry]
name = "saleor"
version = "1.0.0"
description = "Saleor ecommerce platform"
authors = ["Adrian"]

[tool.poetry.dependencies]
python = "^3.11"
django = "^4.0"
djangorestframework = "^3.13"
